In [1]:
#1) Create a 1D array.
import numpy as np

# Create a 1D array of integers from 0 to 9
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Print the array
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [2]:
#2) Create a 2D array with the shape of (3,3)
import numpy as np

# Create a 2D array with the shape of (3,3) filled with zeros
arr = np.zeros((3, 3))

# Print the array
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#3.Create a 3D array with the shape of (2,3,4)
import numpy as np

 
arr = np.zeros((2, 3, 4))
 
print(arr)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
#4) Create a boolean array with the shape of (4,4)
import numpy as np

 
arr = np.full((4, 4), False, dtype=bool)

 
print(arr)


[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [6]:
#5) Create a Numpy array filled with all zeros with the shape of (5,5)
import numpy as np

 
arr = np.zeros((5, 5))

 
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
#6) Create a Numpy array filled with all ones with the shape of (5,5) 
import numpy as np

# Create a 2D array with the shape of (5,5) filled with ones
arr = np.ones((5, 5))

# Print the array
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
#7) Create a 3-D array with the shape of (2,3,4) and Keep integer numbers from 1 to 24.

#Find the total EVEN numbers ADDITION from the given 3-D array. 

import numpy as np

arr = np.arange(1, 25).reshape(2, 3, 4)

print(arr)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [10]:
#8) Create a 3-D array with the shape of (2,3,4) and Keep integer numbers from 1 to 24.

#Find the total ODD numbers ADDITION from the given 3-D array.
 
even_sum = np.sum(arr[arr % 2 == 0])

 
print("The total even numbers addition is:", even_sum)


The total even numbers addition is: 156
